name: concrete-example
channels:
- defaults
- anaconda
- conda-forge
dependencies:
- python=3.7.7
- scikit-learn=0.23.1
- pip
- pip:
  - mlflow==1.10.0
  - mlflow-extend==0.1.6
  - pandas==1.0.5
name: mlflow-env